### ISSUE TITLE
Building OMSysIdent

### ISSUE THREAD

**Issue by tinrabuzin** [OpenModelica/OMSysIdent#3]
Hi, 

I'm trying to build OMSysIdent but when I run 'make -j4' in the build directory it complains that it cannot find the OMSimulator header files ( `fatal error: OMSimulator.h: No such file or directory`) . I assume this is because I haven't properly set up the folder structure?

I tried having both ./OMSimulator/OMSysident, and having separate ./OMSimulator and ./OMSysident folders sharing the same parent folder. With the latter I get `usr/bin/ld: cannot find -lOMSimulator`. 

Also, I've built OMSimulator and it can be run. 

Thanks

**Comment by bernhard-thiele** [comment]
Your second try was the correct folder structure. I can reproduce the linking error using cmake v3.17.0. If I use the more modern cmake `target_link_directories()` command instead of the older`link_directories()` command  it works for me. Commit 57e400d  adds a conditional which uses the newer command if it is available. The intention of keeping the older command is for supporting cmake v3.12.0 which does not yet support  `target_link_directories()`, but maybe it doesn't work as intended. 

Which cmake version are you using? Could you please retry with the latest commit?

**Comment by tinrabuzin** [comment]
Thanks for that. Now I got further but a new error appears.

`CMake Error at src/cmake_install.cmake:76 (file):
  file INSTALL cannot find
  "/OMBUILD/OMSysIdent/../OMSimulator/install/linux/lib/OMSimulator.py": No such file or directory.`

The missing file can be found in `/OMBUILD/OMSimulator/install/linux/lib/OMSimulator/OMSimulator.py`. I guess this also might be due to my cmake version which is 3.16.3? I'll update cmake and try with the newer version.

**Comment by tinrabuzin** [comment]
With cmake version 3.19.0-rc2 or 3.18.4 I still get the same complaint about OMSimulator.py as above.

**Comment by tinrabuzin** [comment]
I updated `./src/CMakeLists.txt` line 34 to `install(FILES ${OMSimulator_ROOT}/lib/OMSimulator/OMSimulator.py DESTINATION lib)`. and then it worked out. I guess this might be due to how I built OMSimulator. I just used the master branch instead of going for one of the releases.

**Comment by bernhard-thiele** [comment]
Sorry for the inconvenience and thanks for the report. OMSimulator changed the install file location of OMSimulator.py at some point. I want to get this hackish build logic more robust in the future.
